export type Evento = {
  id: number,
  evento: string,
  dt: Date,
  lat: number,
  lng: number,
  vel: number,
  punto_red?:string,
  alarma: boolean,
  tempa: number,
  tempb:number,
  axMa: number,
  axMb: number,
  ayMa: number,
  ayMb: number,
  azMa: number,
  azMb: number,
  axmeda:number,
  axmedb:number,
  aymeda:number,
  aymedb:number,
  azmeda:number,
  azmedb:number,
}

export type Circulacion = {
  id: number,
  lat_inicial: number,
  lng_inicial: number,
  lat_final: number,
  lng_final: number,
  dt_inicial: Date,
  dt_final: Date,
  punto_red_inicial?:string,
  punto_red_final?:string,
  abierta: boolean,
  alarma: boolean,
  eventos: Evento[]
}
